### ISSUE TITLE
New version for PyPI 

### ISSUE THREAD

**Issue by JimKuhn** [bcoconni/ValgrindCI#6]
I just ran into the problem fixed in #5.

When will a new release be done to PyPI?  I don't want to build from source for my docker image unless necessary.  In the interim, I may just patch the source during image build if no deployment is imminent.

**Comment by bcoconni** [comment]
Hi @JimKuhn, no problem. I'll take care of that.

**Comment by bcoconni** [comment]
ValgrindCI 0.2.0 has just been released to PyPI.
Let me know if that fixes your problem.

**Comment by bcoconni** [comment]
The lack of feedback is assumed to be positive feedback.
Issue closed.
